apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  selector:
    app: register-app

  ports:
    - port: 7070
      targetPort: 7070

  type: ClusterIP
